title                    : "Almene De Meran Meguimtsop"
name                     : &name "Almene De Meran Meguimtsop"
description              : &description "PhD student in Computer Science at CU Boulder | AI safety & alignment, NLP, Science of Science"
url                      : "https://almene08.github.io"
baseurl                  : ""
repository               : "Almene08/almene08.github.io"